name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.4'

    steps:
      - uses: actions/checkout@v3
      - uses: firehed/lint-php-action@v1
